### PR TITLE
style: format files

### PR DESCRIPTION
**Pull request by ghost**
Just spun `deno fmt`

### CODE REVIEW

**Comment by TymanWasTaken** [comment]
I would have done this earlier, but I personally just don't like how it formats it, I will try and make the formatting better though

**Comment by ghost** [comment]
> I would have done this earlier, but I personally just don't like how it formats it, I will try and make the formatting better though

If you prefer Prettier over builtin linter, feel free to use that instead.

**Comment by TymanWasTaken** [comment]
How would eslint work with deno because usually you just `npm i eslint`

**Comment by ghost** [comment]
> How would eslint work with deno because usually you just `npm i eslint`

You can integrate Node as well as Deno in the project.

**Pull request closed without merging**
